### ISSUE TITLE
TCP connection broken with graal

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-cli#108]
```
 ./build/graal/rsocketcli tcp://localhost:9000 -s wss://rsocket-demo.herokuapp.com/rsocket
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:291)
	at io.ktor.network.selector.SelectableBase.<init>(SelectableJvm.kt:8)
	at io.ktor.network.sockets.NIOSocketImpl.<init>(NIOSocket.kt:22)
	at io.ktor.network.sockets.SocketImpl.<init>(SocketImpl.kt:17)
	at io.ktor.network.sockets.ConnectUtilsJvmKt.connect(ConnectUtilsJvm.kt:18)
	at io.ktor.network.sockets.TcpSocketBuilder.connect(TcpSocketBuilder.kt:38)
	at io.rsocket.kotlin.transport.ktor.TcpClientTransportKt$clientTransport$$inlined$ClientTransport$1.connect(ClientTransport.kt:33)
	at io.rsocket.kotlin.core.RSocketConnector.connectOnce(RSocketConnector.kt:44)
	at io.rsocket.kotlin.core.RSocketConnector.connect(RSocketConnector.kt:35)
	at io.rsocket.cli.ClientKt.buildTcpClient(client.kt:52)
	at io.rsocket.cli.ClientKt.buildClient(client.kt:29)
	at io.rsocket.cli.ClientKt.buildClient$default(client.kt:27)
	at io.rsocket.cli.Main.exec(Main.kt:175)
	at io.rsocket.cli.Main$exec$1.invokeSuspend(Main.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:86)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.rsocket.cli.Main.run(Main.kt:143)
	at io.rsocket.cli.Main$Companion.exec(Main.kt:298)
	at io.rsocket.cli.Main$Companion.main(Main.kt:282)
	at io.rsocket.cli.Main.main(Main.kt)
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: readHandlerReference
	at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.<init>(AtomicReferenceFieldUpdater.java:120)
	at java.util.concurrent.atomic.AtomicReferenceFieldUpdater.newUpdater(AtomicReferenceFieldUpdater.java:116)
	at io.ktor.network.selector.InterestSuspensionsMap.<clinit>(InterestSuspensionsMap.kt:71)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
	... 25 more
Caused by: java.lang.NoSuchFieldException: readHandlerReference
	at java.lang.Class.getDeclaredField(DynamicHub.java:2411)
	at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.<init>(AtomicReferenceFieldUpdater.java:115)
	... 29 more
```

**Comment by sureshg** [comment]
I am trying the new rsocket-kotlin with graalvm-ce native image and hits with the same error

```
Exception in thread "pool-2-thread-1" java.lang.NoClassDefFoundError: Could not initialize class io.ktor.network.selector.InterestSuspensionsMap
	at io.ktor.network.selector.SelectableBase.<init>(SelectableJvm.kt:12)
	at io.ktor.network.sockets.NIOSocketImpl.<init>(NIOSocketImpl.kt:22)
	at io.ktor.network.sockets.SocketImpl.<init>(SocketImpl.kt:14)
```	

Any idea why `io.ktor.network.selector.InterestSuspensionsMap` reflect config is not generated when running with tracing agent (` java -agentlib:native-image-agent=config-output-dir=config -jar ...`) ? Had to add this config explicitly

**Comment by yschimke** [comment]
I'll take a look, thanks for the heads up.

**Comment by yschimke** [comment]
@sureshg with this build it appears to be working https://github.com/rsocket/rsocket-cli/pull/124
