### ISSUE TITLE
Convert UriUtils.java to UriUtils.kt

### ISSUE THREAD

**Issue by linux-china** [rsocket/rsocket-cli#94]
UriUtils.java is ignored by Java compiler because it's in src/main/kotlin, and  not src/main/java.   

https://github.com/rsocket/rsocket-cli/blob/master/src/main/kotlin/io/rsocket/cli/uri/UriUtils.java

It will trigger bug when using websocket. 

```
 ./rsocket-cli -i "pong" --server --debug ws://localhost:42252
Exception in thread "main" java.lang.NoClassDefFoundError: io/rsocket/cli/uri/UriUtils
	at io.rsocket.cli.uri.WebsocketUriHandler.buildServer(WebsocketUriHandler.kt:52)
	at io.rsocket.cli.uri.UriTransportRegistry.serverForUri(UriTransportRegistry.kt:57)
	at io.rsocket.cli.Main.buildServer(Main.kt:207)
	at io.rsocket.cli.Main.exec(Main.kt:180)
	at io.rsocket.cli.Main$run$1.invokeSuspend(Main.kt:140)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.rsocket.cli.Main.run(Main.kt:139)
	at io.rsocket.cli.Main$Companion.exec(Main.kt:388)
	at io.rsocket.cli.Main$Companion.main(Main.kt:372)
	at io.rsocket.cli.Main.main(Main.kt)
Caused by: java.lang.ClassNotFoundException: io.rsocket.cli.uri.UriUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 17 more
```

**Comment by yschimke** [comment]
Can fix, unless you are planning.
